language: node_js
node_js:
  - "14.16"
sudo: required

branches:
  only:
    - master

before_script:
  - npm i

script:
  - npm run lint
  - npm run test:unit
  - npm run coveralls
  - npm run build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
