language: node_js
node_js:
  - "14.16"
sudo: required

branches:
  only:
    - master

before_script:
  - npm i

script:
  - npm run lint
  - npm run test:unit
  - npm run coveralls
  - npm run build --prod

before_deploy:
    - zip -r dist.zip dist
    - git config --local user.name "$GITHUB_USER"
    - git config --local user.email "$GITHUB_EMAIL"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist.zip"
  skip_cleanup: true
  on:
    branch: master
